"""
core/commands/completion.py — Shell completion generator
=========================================================

Generates Bash, Zsh, and Fish completion scripts for ``tool.py``.

Usage::

    tool completion bash > ~/.local/share/bash-completion/completions/tool
    tool completion zsh  > ~/.zfunc/_tool
    tool completion fish > ~/.config/fish/completions/tool.fish
    tool completion --install   # auto-install for current shell
"""
from __future__ import annotations

import os
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Command + subcommand structure (manually kept in sync)
# ---------------------------------------------------------------------------

COMMANDS: dict[str, list[str]] = {
    "build":    ["check", "clean", "extension", "deploy", "docker"],
    "deps":     ["lock", "verify", "list", "conan-profile"],
    "doc":      ["serve", "list", "build"],
    "format":   ["check", "tidy-fix", "iwyu"],
    "generate": [],
    "lib":      ["add", "remove", "rename", "move", "list", "info", "tree", "doctor", "deps", "export"],
    "license":  ["recommend", "list"],
    "new":      [],
    "perf":     ["track", "check-budget", "stat", "record", "bench", "size", "build-time",
                 "graph", "godbolt", "valgrind", "concurrency", "vec", "autotune",
                 "size-diff", "promote", "hw-recommend"],
    "plugins":  [],
    "presets":  ["generate", "list", "validate"],
    "release":  ["bump", "set", "set-revision", "tag", "publish", "unpublish"],
    "security": ["scan"],
    "session":  ["save", "load", "set"],
    "sol":      ["preset", "ci", "doctor", "target", "sysroot"],
    "tui":      [],
    "validate": [],
}

GLOBAL_FLAGS = [
    "--verbose", "--json", "--yes", "--dry-run", "--help", "--version",
    "--install", "--recreate", "--skip-ci", "--ci-mode",
    "--report-artifact", "--retain-days",
]


def _bash_completion() -> str:
    cmds = " ".join(sorted(COMMANDS))
    flags = " ".join(GLOBAL_FLAGS)

    subcmd_cases = []
    for cmd, subs in sorted(COMMANDS.items()):
        if subs:
            subcmd_cases.append(f"        {cmd}) COMPREPLY=( $(compgen -W \"{' '.join(subs)}\" -- \"$cur\") );;")

    return f'''# Bash completion for tool.py
# Generated by: tool completion bash

_tool_completions() {{
    local cur prev cmds
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"
    cmds="{cmds}"

    # Complete global flags
    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "{flags}" -- "$cur") )
        return
    fi

    # Complete subcommands
    case "$prev" in
{chr(10).join(subcmd_cases)}
        tool|tool.py)
            COMPREPLY=( $(compgen -W "$cmds" -- "$cur") )
            ;;
        *)
            # If the previous word is a known command, offer subcommands
            for cmd in $cmds; do
                if [[ "${{COMP_WORDS[1]}}" == "$cmd" ]]; then
                    case "$cmd" in
{chr(10).join(f"                        {cmd}) COMPREPLY=( $(compgen -W \"{' '.join(subs)}\" -- \"$cur\") );;" for cmd, subs in sorted(COMMANDS.items()) if subs)}
                    esac
                    return
                fi
            done
            COMPREPLY=( $(compgen -W "$cmds" -- "$cur") )
            ;;
    esac
}}

complete -F _tool_completions tool
complete -F _tool_completions tool.py
complete -F _tool_completions ./tool.py
'''


def _zsh_completion() -> str:
    cmds = sorted(COMMANDS)
    subcmd_cases = []
    for cmd in cmds:
        subs = COMMANDS[cmd]
        if subs:
            subcmd_cases.append(f"        {cmd}) _values 'subcommand' {' '.join(subs)};;")
        else:
            subcmd_cases.append(f"        {cmd}) ;;")

    return f'''#compdef tool tool.py
# Zsh completion for tool.py
# Generated by: tool completion zsh

_tool() {{
    local -a commands
    commands=(
{chr(10).join(f"        '{cmd}'" for cmd in cmds)}
    )

    _arguments -C \\
        '--verbose[Enable debug logging]' \\
        '--json[Output results in JSON]' \\
        '--yes[Auto-confirm non-interactive]' \\
        '--dry-run[Preview only]' \\
        '--help[Show help]' \\
        '--version[Show version]' \\
        '1:command:->cmd' \\
        '*::arg:->args'

    case "$state" in
        cmd)
            _describe 'command' commands
            ;;
        args)
            case "${{words[1]}}" in
{chr(10).join(subcmd_cases)}
            esac
            ;;
    esac
}}

_tool "$@"
'''


def _fish_completion() -> str:
    lines = [
        "# Fish completion for tool.py",
        "# Generated by: tool completion fish",
        "",
    ]

    cmds = sorted(COMMANDS)
    for cmd in cmds:
        lines.append(f"complete -c tool -n '__fish_use_subcommand' -a '{cmd}'")

    for cmd, subs in sorted(COMMANDS.items()):
        for sub in subs:
            lines.append(
                f"complete -c tool -n '__fish_seen_subcommand_from {cmd}' -a '{sub}'"
            )

    for flag in GLOBAL_FLAGS:
        short = flag.lstrip("-")
        lines.append(f"complete -c tool -l '{short}'")

    lines.append("")
    return "\n".join(lines)


def _install_completion(shell: str) -> None:
    """Auto-install completion for the detected shell."""
    if shell == "bash":
        target = Path.home() / ".local" / "share" / "bash-completion" / "completions" / "tool"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_bash_completion(), encoding="utf-8")
        print(f"Installed: {target}")
    elif shell == "zsh":
        target = Path.home() / ".zfunc" / "_tool"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_zsh_completion(), encoding="utf-8")
        print(f"Installed: {target}")
        print("Make sure ~/.zfunc is in your $fpath (add: fpath=(~/.zfunc $fpath))")
    elif shell == "fish":
        target = Path.home() / ".config" / "fish" / "completions" / "tool.fish"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_fish_completion(), encoding="utf-8")
        print(f"Installed: {target}")
    else:
        print(f"Unknown shell: {shell}", file=sys.stderr)
        sys.exit(1)


def _detect_shell() -> str:
    shell = os.environ.get("SHELL", "")
    if "zsh" in shell:
        return "zsh"
    if "fish" in shell:
        return "fish"
    return "bash"


def main(argv: list[str] | None = None) -> None:
    argv = argv or []

    if "--help" in argv or "-h" in argv:
        print(__doc__)
        sys.exit(0)

    install = "--install" in argv
    args = [a for a in argv if not a.startswith("-")]

    if install:
        shell = args[0] if args else _detect_shell()
        _install_completion(shell)
        return

    if not args:
        print("Usage: tool completion {bash|zsh|fish} [--install]", file=sys.stderr)
        sys.exit(1)

    shell = args[0].lower()
    generators = {
        "bash": _bash_completion,
        "zsh": _zsh_completion,
        "fish": _fish_completion,
    }
    if shell not in generators:
        print(f"Unknown shell: {shell}. Supported: bash, zsh, fish", file=sys.stderr)
        sys.exit(1)

    print(generators[shell]())
