#!/usr/bin/env python3
"""
core/commands/deps.py — Dependency management: lock files for vcpkg, Conan, and pip.

Subcommands:
  lock   — generate lock files for all detected dependency managers
  verify — check that lock files are present and up-to-date
  list   — list dependencies from all manifests
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
from pathlib import Path

from core.utils.common import Logger, CLIResult, run_proc, PROJECT_ROOT

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

VCPKG_JSON = PROJECT_ROOT / "vcpkg.json"
VCPKG_LOCK = PROJECT_ROOT / "vcpkg.lock.json"
CONAN_FILE = PROJECT_ROOT / "conanfile.py"
CONAN_LOCK = PROJECT_ROOT / "conan.lock"
REQ_FILE = PROJECT_ROOT / "requirements-dev.txt"
PIP_LOCK = PROJECT_ROOT / "requirements-dev.lock.txt"


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


# ---------------------------------------------------------------------------
# vcpkg lock
# ---------------------------------------------------------------------------

def _lock_vcpkg(dry_run: bool) -> bool:
    """Generate vcpkg.lock.json from vcpkg.json manifest."""
    if not VCPKG_JSON.exists():
        Logger.info("  vcpkg.json not found — skipping")
        return True

    Logger.info(f"  vcpkg.json detected: {VCPKG_JSON.name}")
    manifest = json.loads(VCPKG_JSON.read_text(encoding="utf-8"))
    dependencies = manifest.get("dependencies", [])

    # Normalize dependencies to name+version-constraint records
    lock_entries: list[dict] = []
    for dep in dependencies:
        if isinstance(dep, str):
            lock_entries.append({"name": dep, "version-constraint": "*"})
        elif isinstance(dep, dict):
            lock_entries.append({
                "name": dep.get("name", "?"),
                "version-constraint": dep.get("version>=", dep.get("version", "*")),
                "features": dep.get("features", []),
                "platform": dep.get("platform", ""),
            })

    # Try to enrich with installed versions via `vcpkg list --x-json`
    vcpkg_bin = shutil.which("vcpkg")
    installed: dict[str, str] = {}
    if vcpkg_bin:
        try:
            result = subprocess.run(
                [vcpkg_bin, "list", "--x-json"],
                capture_output=True, text=True, timeout=30
            )
            if result.returncode == 0 and result.stdout.strip():
                vcpkg_list = json.loads(result.stdout)
                for pkg_id, info in vcpkg_list.items():
                    # pkg_id format: "zlib:x64-linux" or "zlib@1.2.11#0:x64-linux"
                    name = pkg_id.split(":")[0].split("@")[0]
                    version = info.get("version", "*")
                    installed[name] = version
        except (subprocess.TimeoutExpired, json.JSONDecodeError, OSError):
            pass

    for entry in lock_entries:
        if entry["name"] in installed:
            entry["resolved-version"] = installed[entry["name"]]

    lock = {
        "$comment": "Auto-generated by 'tool deps lock'. Do not edit manually.",
        "manifest-hash": _sha256_file(VCPKG_JSON),
        "dependencies": lock_entries,
    }

    if dry_run:
        Logger.info(f"  [dry-run] Would write {VCPKG_LOCK}")
        Logger.info(f"  {len(lock_entries)} dependency entries")
        return True

    VCPKG_LOCK.write_text(json.dumps(lock, indent=2, sort_keys=False), encoding="utf-8")
    Logger.info(f"  Written: {VCPKG_LOCK} ({len(lock_entries)} entries)")
    return True


# ---------------------------------------------------------------------------
# Conan lock
# ---------------------------------------------------------------------------

def _lock_conan(dry_run: bool) -> bool:
    """Generate conan.lock using 'conan lock create' or a static snapshot."""
    if not CONAN_FILE.exists():
        Logger.info("  conanfile.py not found — skipping")
        return True

    Logger.info(f"  conanfile.py detected: {CONAN_FILE.name}")
    conan_bin = shutil.which("conan")

    if conan_bin:
        Logger.info("  Running: conan lock create .")
        if dry_run:
            Logger.info(f"  [dry-run] Would run: conan lock create . --lockfile-out {CONAN_LOCK}")
            return True
        rc = run_proc(
            [conan_bin, "lock", "create", ".",
             "--lockfile-out", str(CONAN_LOCK)],
            cwd=str(PROJECT_ROOT), check=False
        )
        if rc == 0:
            Logger.info(f"  Written: {CONAN_LOCK}")
        else:
            Logger.warn("  'conan lock create' failed — writing manifest-hash snapshot")
            _write_conan_lock_snapshot(dry_run)
        return rc == 0
    else:
        Logger.warn("  conan not found — writing manifest-hash snapshot (install conan for full lock)")
        return _write_conan_lock_snapshot(dry_run)


def _write_conan_lock_snapshot(dry_run: bool) -> bool:
    lock = {
        "$comment": "Snapshot lock — install conan and run 'tool deps lock' for full lock.",
        "manifest-hash": _sha256_file(CONAN_FILE),
        "conan-version": "2.x",
    }
    if dry_run:
        Logger.info(f"  [dry-run] Would write {CONAN_LOCK}")
        return True
    CONAN_LOCK.write_text(json.dumps(lock, indent=2), encoding="utf-8")
    Logger.info(f"  Written: {CONAN_LOCK}")
    return True


# ---------------------------------------------------------------------------
# pip lock
# ---------------------------------------------------------------------------

def _lock_pip(dry_run: bool) -> bool:
    """Generate pinned requirements lock from requirements-dev.txt via pip-compile or pip freeze."""
    if not REQ_FILE.exists():
        Logger.info("  requirements-dev.txt not found — skipping")
        return True

    Logger.info(f"  requirements-dev.txt detected")

    pip_compile = shutil.which("pip-compile")
    if pip_compile:
        Logger.info("  Running: pip-compile requirements-dev.txt")
        if dry_run:
            Logger.info(f"  [dry-run] Would write {PIP_LOCK}")
            return True
        rc = run_proc(
            [pip_compile, str(REQ_FILE), "--output-file", str(PIP_LOCK),
             "--quiet", "--no-header"],
            cwd=str(PROJECT_ROOT), check=False
        )
        if rc == 0:
            Logger.info(f"  Written: {PIP_LOCK}")
            return True

    # Fallback: pip freeze (only current env packages)
    Logger.warn("  pip-compile not found (install pip-tools). Using 'pip freeze' fallback.")
    if dry_run:
        Logger.info(f"  [dry-run] Would write {PIP_LOCK}")
        return True
    result = subprocess.run(["pip", "freeze"], capture_output=True, text=True)
    if result.returncode == 0:
        header = "# Generated by 'tool deps lock' — pip freeze snapshot\n"
        PIP_LOCK.write_text(header + result.stdout, encoding="utf-8")
        Logger.info(f"  Written: {PIP_LOCK}")
        return True

    Logger.error("  pip freeze failed")
    return False


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

def _cmd_lock(args) -> CLIResult:
    """Generate lock files for all detected dependency managers."""
    dry_run: bool = getattr(args, "dry_run", False)
    managers: list[str] = getattr(args, "managers", ["vcpkg", "conan", "pip"])

    Logger.info("Generating dependency lock files...")
    if dry_run:
        Logger.info("  (dry-run mode — no files written)\n")

    results = {}

    if "vcpkg" in managers:
        Logger.info("\n[vcpkg]")
        results["vcpkg"] = _lock_vcpkg(dry_run)

    if "conan" in managers:
        Logger.info("\n[conan]")
        results["conan"] = _lock_conan(dry_run)

    if "pip" in managers:
        Logger.info("\n[pip]")
        results["pip"] = _lock_pip(dry_run)

    all_ok = all(results.values())
    msg = "Lock files generated" if all_ok else "Some lock files failed"
    Logger.info(f"\n{'✓' if all_ok else '✗'} {msg}: {results}")
    return CLIResult(success=all_ok, code=0 if all_ok else 1, message=msg, data=results)


def _cmd_verify(args) -> CLIResult:
    """Verify lock files are present and consistent with their manifests."""
    issues: list[str] = []

    # vcpkg
    if VCPKG_JSON.exists():
        if not VCPKG_LOCK.exists():
            issues.append("vcpkg.lock.json missing — run 'tool deps lock'")
        else:
            lock = json.loads(VCPKG_LOCK.read_text(encoding="utf-8"))
            if lock.get("manifest-hash") != _sha256_file(VCPKG_JSON):
                issues.append("vcpkg.lock.json is stale (vcpkg.json changed) — run 'tool deps lock'")
            else:
                Logger.info("  ✓ vcpkg.lock.json up-to-date")

    # conan
    if CONAN_FILE.exists():
        if not CONAN_LOCK.exists():
            issues.append("conan.lock missing — run 'tool deps lock'")
        else:
            lock = json.loads(CONAN_LOCK.read_text(encoding="utf-8"))
            current_hash = _sha256_file(CONAN_FILE)
            stored_hash = lock.get("manifest-hash", "")
            if stored_hash and stored_hash != current_hash:
                issues.append("conan.lock is stale (conanfile.py changed) — run 'tool deps lock'")
            else:
                Logger.info("  ✓ conan.lock up-to-date")

    # pip
    if REQ_FILE.exists():
        if not PIP_LOCK.exists():
            Logger.info("  ℹ requirements-dev.lock.txt absent — run 'tool deps lock --managers pip' with pip-tools installed")
        else:
            Logger.info("  ✓ requirements-dev.lock.txt present")

    if issues:
        for iss in issues:
            Logger.error(f"  ✗ {iss}")
        return CLIResult(success=False, code=1, message=f"{len(issues)} lock issue(s) found", data={"issues": issues})

    return CLIResult(success=True, message="All lock files present and up-to-date")


def _cmd_list(args) -> CLIResult:
    """List dependencies from all manifests."""
    all_deps: dict[str, list] = {}

    # vcpkg
    if VCPKG_JSON.exists():
        manifest = json.loads(VCPKG_JSON.read_text(encoding="utf-8"))
        deps = manifest.get("dependencies", [])
        all_deps["vcpkg"] = deps
        Logger.info("[vcpkg]")
        for d in deps:
            name = d if isinstance(d, str) else d.get("name", "?")
            Logger.info(f"  {name}")

    # conan — parse require() calls from conanfile.py
    if CONAN_FILE.exists():
        Logger.info("\n[conan]")
        conan_deps = []
        for line in CONAN_FILE.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if stripped.startswith("self.requires("):
                dep = stripped.removeprefix("self.requires(").strip().strip(')"').strip("'")
                conan_deps.append(dep)
                Logger.info(f"  {dep}")
        all_deps["conan"] = conan_deps

    # pip
    if REQ_FILE.exists():
        Logger.info("\n[pip]")
        pip_deps = []
        for line in REQ_FILE.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if stripped and not stripped.startswith("#"):
                pip_deps.append(stripped)
                Logger.info(f"  {stripped}")
        all_deps["pip"] = pip_deps

    if not all_deps:
        return CLIResult(success=False, code=1, message="No dependency manifests found")

    total = sum(len(v) for v in all_deps.values())
    return CLIResult(success=True, message=f"{total} dependencies found", data=all_deps)


# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------

def deps_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="tool deps", description="Dependency lock file management")
    sub = parser.add_subparsers(dest="subcommand")

    # lock
    p = sub.add_parser("lock", help="Generate lock files for all dependency managers")
    p.add_argument("--dry-run", action="store_true", dest="dry_run",
                   help="Preview what would be written without creating files")
    p.add_argument("--managers", nargs="+", default=["vcpkg", "conan", "pip"],
                   choices=["vcpkg", "conan", "pip"],
                   help="Which managers to lock (default: all)")
    p.set_defaults(func=_cmd_lock)

    # verify
    p = sub.add_parser("verify", help="Verify lock files are present and consistent")
    p.set_defaults(func=_cmd_verify)

    # list
    p = sub.add_parser("list", help="List dependencies from all manifests")
    p.set_defaults(func=_cmd_list)

    return parser


def main(argv: list[str]) -> None:
    parser = deps_parser()
    args = parser.parse_args(argv if argv else [])
    if hasattr(args, "func"):
        args.func(args).exit()
    else:
        parser.print_help()
