"""
core/generator/docs.py — Documentation scaffolding generator component
======================================================================

Generates documentation configuration and skeleton files based on
``tool.toml [doc]`` settings.

Supported documentation backends (gated by ``doc.engine``):

- **doxygen** (default) — Generates ``Doxyfile`` for C++ API docs
- **mkdocs** — Generates ``mkdocs.yml`` + ``docs/index.md``
- **sphinx** — Generates ``docs/conf.py`` + ``docs/index.rst``

The ``doc.generate_api_docs`` flag (default: true) controls whether the
engine-specific config is produced. Setting it to false still generates
the markdown skeleton docs.

Multiple engines can be enabled simultaneously via a list:
``doc.engine = ["doxygen", "mkdocs"]``
"""
from __future__ import annotations

import json
from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path
    from core.generator.engine import ProjectContext


# ---------------------------------------------------------------------------
# Doxyfile generation
# ---------------------------------------------------------------------------

def _gen_doxyfile(ctx: "ProjectContext") -> str:
    """Generate a Doxyfile for Doxygen."""
    name = ctx.name or "CppProject"
    version = ctx.version or "1.0.0"
    description = ctx.description or ""

    # Collect source directories
    input_dirs = ["libs/", "apps/"]
    exclude_dirs = ["build/", "external/", "_deps/", ".git/"]

    # Dot graph support
    have_dot = ctx.docs.get("doxygen_dot", True)
    extract_all = ctx.docs.get("doxygen_extract_all", True)

    return f"""# Doxyfile — AUTO-GENERATED by tool generate
# Edit tool.toml [doc] and re-run `tool generate` to update.

PROJECT_NAME           = "{name}"
PROJECT_NUMBER         = "{version}"
PROJECT_BRIEF          = "{description}"
OUTPUT_DIRECTORY       = docs/api
INPUT                  = {" ".join(input_dirs)}
RECURSIVE              = YES
FILE_PATTERNS          = *.h *.hpp *.cpp *.cc *.cxx *.h++ *.c++

EXCLUDE                = {" ".join(exclude_dirs)}
EXCLUDE_PATTERNS       = */build/* */external/* */_deps/* */test/*

# Output format
GENERATE_HTML          = YES
GENERATE_LATEX         = NO
GENERATE_XML           = YES
HTML_OUTPUT            = html
XML_OUTPUT             = xml
HTML_COLORSTYLE        = LIGHT

# Extraction
EXTRACT_ALL            = {"YES" if extract_all else "NO"}
EXTRACT_PRIVATE        = NO
EXTRACT_STATIC         = YES
EXTRACT_LOCAL_CLASSES  = YES

# Diagrams
HAVE_DOT               = {"YES" if have_dot else "NO"}
DOT_IMAGE_FORMAT       = svg
INTERACTIVE_SVG        = YES
CALL_GRAPH             = {"YES" if have_dot else "NO"}
CALLER_GRAPH           = {"YES" if have_dot else "NO"}
CLASS_DIAGRAMS         = YES
COLLABORATION_GRAPH    = YES

# Code browsing
SOURCE_BROWSER         = YES
INLINE_SOURCES         = NO
REFERENCED_BY_RELATION = YES
REFERENCES_RELATION    = YES
STRIP_FROM_PATH        = .

# Warnings
WARN_IF_UNDOCUMENTED   = YES
WARN_IF_DOC_ERROR      = YES
WARN_NO_PARAMDOC       = YES
WARN_AS_ERROR          = NO

# Preprocessing
ENABLE_PREPROCESSING   = YES
MACRO_EXPANSION        = YES
PREDEFINED             = DOXYGEN_SHOULD_SKIP_THIS

# Search
SEARCHENGINE           = YES
"""


# ---------------------------------------------------------------------------
# MkDocs generation
# ---------------------------------------------------------------------------

def _gen_mkdocs_yml(ctx: "ProjectContext") -> str:
    """Generate mkdocs.yml configuration."""
    name = ctx.name or "CppProject"
    description = ctx.description or ""
    author = ctx.author or ""
    theme = ctx.docs.get("mkdocs_theme", "material")

    yml = f"""# mkdocs.yml — AUTO-GENERATED by tool generate
# Edit tool.toml [doc] and re-run `tool generate` to update.

site_name: "{name}"
site_description: "{description}"
site_author: "{author}"

theme:
  name: {theme}
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: api-reference.md
  - Contributing: contributing.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
"""
    return yml


# ---------------------------------------------------------------------------
# Sphinx generation
# ---------------------------------------------------------------------------

def _gen_sphinx_conf(ctx: "ProjectContext") -> str:
    """Generate docs/conf.py for Sphinx."""
    name = ctx.name or "CppProject"
    version = ctx.version or "1.0.0"
    author = ctx.author or ""

    # Breathe integration for Doxygen XML
    engines = _resolve_engines(ctx)
    use_breathe = "doxygen" in engines

    breathe_block = ""
    breathe_ext = ""
    if use_breathe:
        breathe_ext = "'breathe',"
        breathe_block = f"""
# Breathe (Doxygen XML integration)
breathe_projects = {{"{name}": "../docs/api/xml"}}
breathe_default_project = "{name}"
"""

    return f'''# Sphinx conf.py — AUTO-GENERATED by tool generate
# Edit tool.toml [doc] and re-run `tool generate` to update.

project = "{name}"
version = "{version}"
author = "{author}"
copyright = "{author}"

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.todo',
    {breathe_ext}
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]
{breathe_block}'''


def _gen_sphinx_index(ctx: "ProjectContext") -> str:
    """Generate docs/index.rst for Sphinx."""
    name = ctx.name or "CppProject"
    underline = "=" * len(name)

    return f"""{name}
{underline}

.. toctree::
   :maxdepth: 2
   :caption: Contents:

   getting-started
   api-reference
   contributing

Indices and tables
==================

* :ref:`genindex`
* :ref:`search`
"""


# ---------------------------------------------------------------------------
# Markdown doc skeleton
# ---------------------------------------------------------------------------

def _gen_docs_index(ctx: "ProjectContext") -> str:
    """Generate docs/index.md — main docs landing page."""
    name = ctx.name or "CppProject"
    version = ctx.version or "1.0.0"
    description = ctx.description or ""
    libs = ctx.libs if ctx.libs else []
    apps = ctx.apps if ctx.apps else []

    lib_lines = ""
    if libs:
        lib_items = "\n".join(f"- **{lib.get('name', '?')}** — `libs/{lib.get('name', '?')}/`" for lib in libs)
        lib_lines = f"\n## Libraries\n\n{lib_items}\n"

    app_lines = ""
    if apps:
        app_items = "\n".join(f"- **{app.get('name', '?')}** — `apps/{app.get('name', '?')}/`" for app in apps)
        app_lines = f"\n## Applications\n\n{app_items}\n"

    return f"""# {name}

{description}

**Version:** {version}
{lib_lines}{app_lines}
## Quick Start

```bash
# Build
python3 scripts/tool.py build

# Run tests
python3 scripts/tool.py build check --no-sync

# Generate docs
python3 scripts/tool.py doc build
```

## Documentation

- [Getting Started](getting-started.md)
- [API Reference](api-reference.md)
- [Contributing](contributing.md)
"""


def _gen_getting_started(ctx: "ProjectContext") -> str:
    """Generate docs/getting-started.md."""
    name = ctx.name or "CppProject"
    return f"""# Getting Started with {name}

## Prerequisites

- C++ compiler (GCC 11+, Clang 14+, or MSVC 2022+)
- CMake 3.25+
- Python 3.10+
- Ninja (recommended)

## Building

```bash
# Clone and enter
git clone <repository-url>
cd {name}

# Setup development environment
python3 scripts/tool.py setup --install

# Build
python3 scripts/tool.py build

# Run tests
python3 scripts/tool.py build check --no-sync
```

## Project Structure

```
apps/           Executable applications
libs/           Libraries (each independent, versioned)
tests/          Test suites (unit, fuzz)
cmake/          CMake modules and toolchains
scripts/        Build automation and tooling
docs/           Documentation
```

## Next Steps

- Read the [API Reference](api-reference.md) for library documentation
- See [Contributing](contributing.md) to contribute to the project
"""


def _gen_api_reference(ctx: "ProjectContext") -> str:
    """Generate docs/api-reference.md."""
    name = ctx.name or "CppProject"
    libs = ctx.libs if ctx.libs else []

    sections = ""
    for lib in libs:
        lib_name = lib.get("name", "?")
        sections += f"""
### {lib_name}

- Header: `libs/{lib_name}/include/{lib_name}/`
- Source: `libs/{lib_name}/src/`
- Tests: `tests/unit/{lib_name}/`

"""

    engines = _resolve_engines(ctx)
    doxygen_note = ""
    if "doxygen" in engines:
        doxygen_note = """
> **Tip:** Run `doxygen Doxyfile` to generate full API documentation in `docs/api/html/`.
"""

    return f"""# API Reference — {name}

{doxygen_note}
## Libraries
{sections if sections else "No libraries configured."}
"""


def _gen_contributing(ctx: "ProjectContext") -> str:
    """Generate docs/contributing.md."""
    name = ctx.name or "CppProject"
    return f"""# Contributing to {name}

## Development Setup

```bash
python3 scripts/tool.py setup --install
```

## Code Style

- **C++:** `PascalCase` for classes/structs, `lower_case` for functions/variables
- **Formatting:** `.clang-format` enforced — run `python3 scripts/tool.py format`
- **Static Analysis:** `python3 scripts/tool.py format tidy-fix`

## Testing

```bash
# Run all tests
python3 scripts/tool.py build check --no-sync

# Run specific library tests
cmake --build --preset gcc-debug-static-x86_64 --target <lib>_tests
```

## Pull Request Checklist

- [ ] All tests pass
- [ ] Code formatted with clang-format
- [ ] Documentation updated if needed
- [ ] No new compiler warnings
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _resolve_engines(ctx: "ProjectContext") -> list[str]:
    """Resolve the list of doc engines from config."""
    raw = ctx.docs.get("engine", "doxygen")
    if isinstance(raw, str):
        engines = [e.strip().lower() for e in raw.split(",") if e.strip()]
    elif isinstance(raw, (list, tuple)):
        engines = [str(e).strip().lower() for e in raw if str(e).strip()]
    else:
        engines = ["doxygen"]
    return engines if engines else ["doxygen"]


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def generate_all(ctx: "ProjectContext", target_dir: "Path") -> dict[str, str]:
    """Generate documentation files based on [doc] config."""
    from core.generator.engine import is_feature_enabled

    files: dict[str, str] = {}

    # Always generate markdown skeleton docs (unless docs feature is entirely off)
    docs_enabled = is_feature_enabled(ctx, "docs", default=ctx.docs.get("generate", True))
    if not docs_enabled:
        return files

    # Markdown doc skeleton — always generated when docs are enabled
    files["docs/index.md"] = _gen_docs_index(ctx)
    files["docs/getting-started.md"] = _gen_getting_started(ctx)
    files["docs/api-reference.md"] = _gen_api_reference(ctx)
    files["docs/contributing.md"] = _gen_contributing(ctx)

    # API docs engine configs — gated by doc.generate_api_docs
    generate_api = ctx.docs.get("generate_api_docs", True)
    if not generate_api:
        return files

    engines = _resolve_engines(ctx)

    if "doxygen" in engines:
        files["Doxyfile"] = _gen_doxyfile(ctx)

    if "mkdocs" in engines:
        files["mkdocs.yml"] = _gen_mkdocs_yml(ctx)

    if "sphinx" in engines:
        files["docs/conf.py"] = _gen_sphinx_conf(ctx)
        files["docs/index.rst"] = _gen_sphinx_index(ctx)

    return files
