# cmake/Sanitizers.cmake

function(enable_sanitizers target)
    if(MSVC)
        # MSVC Sanitizer support (limited compared to GCC/Clang)
        if(ENABLE_ASAN)
            target_compile_options(${target} PRIVATE /fsanitize=address)
        endif()
    else()
        set(SAN_FLAGS "")
        if(ENABLE_ASAN)
            list(APPEND SAN_FLAGS "-fsanitize=address")
        endif()
        if(ENABLE_UBSAN)
            list(APPEND SAN_FLAGS "-fsanitize=undefined")
        endif()
        if(ENABLE_TSAN)
            if(ENABLE_ASAN OR ENABLE_UBSAN)
                message(FATAL_ERROR "Thread Sanitizer (TSan) cannot be used with ASan or UBSan.")
            endif()
            list(APPEND SAN_FLAGS "-fsanitize=thread")
        endif()

        if(NOT "${SAN_FLAGS}" STREQUAL "")
            target_compile_options(${target} PRIVATE ${SAN_FLAGS} -fno-omit-frame-pointer)
            target_link_options(${target} PUBLIC ${SAN_FLAGS})
        endif()
    endif()
endfunction()
