# cmake/Sanitizers.cmake

function(enable_sanitizers target)
    string(TOUPPER ${target} _tgt_upper)
    
    # Resolve ASAN: Target override OR Global setting
    set(_asan_var "${_tgt_upper}_ENABLE_ASAN")
    if(DEFINED ${_asan_var})
        set(_local_asan ${${_asan_var}})
    else()
        set(_local_asan ${ENABLE_ASAN})
    endif()

    # Resolve UBSAN: Target override OR Global setting
    set(_ubsan_var "${_tgt_upper}_ENABLE_UBSAN")
    if(DEFINED ${_ubsan_var})
        set(_local_ubsan ${${_ubsan_var}})
    else()
        set(_local_ubsan ${ENABLE_UBSAN})
    endif()

    # Resolve TSAN: Target override OR Global setting
    set(_tsan_var "${_tgt_upper}_ENABLE_TSAN")
    if(DEFINED ${_tsan_var})
        set(_local_tsan ${${_tsan_var}})
    else()
        set(_local_tsan ${ENABLE_TSAN})
    endif()

    if(MSVC)
        # MSVC Sanitizer support (limited compared to GCC/Clang)
        if(_local_asan)
            target_compile_options(${target} PRIVATE /fsanitize=address)
        endif()
    else()
        set(SAN_FLAGS "")
        if(_local_asan)
            list(APPEND SAN_FLAGS "-fsanitize=address")
        endif()
        if(_local_ubsan)
            list(APPEND SAN_FLAGS "-fsanitize=undefined")
        endif()
        if(_local_tsan)
            if(_local_asan OR _local_ubsan)
                message(FATAL_ERROR "Thread Sanitizer (TSan) cannot be used with ASan or UBSan on target: ${target}")
            endif()
            list(APPEND SAN_FLAGS "-fsanitize=thread")
        endif()

        if(NOT "${SAN_FLAGS}" STREQUAL "")
            target_compile_options(${target} PRIVATE ${SAN_FLAGS} -fno-omit-frame-pointer)
            target_link_options(${target} PUBLIC ${SAN_FLAGS})
            message(STATUS "Sanitizers enabled for target ${target}: ${SAN_FLAGS}")
        endif()
    endif()
endfunction()
