# cmake/StaticAnalyzers.cmake

function(enable_static_analysis)
    if(ENABLE_CLANG_TIDY)
        find_program(CLANG_TIDY_PATH clang-tidy)
        if(CLANG_TIDY_PATH)
            message(STATUS "Found clang-tidy: ${CLANG_TIDY_PATH}")
            set(TIDY_FLAGS "${CLANG_TIDY_PATH};-extra-arg=-Wno-unknown-warning-option")
            if(ENABLE_WERROR)
                list(APPEND TIDY_FLAGS "-warnings-as-errors=*")
            endif()
            set(CMAKE_CXX_CLANG_TIDY "${TIDY_FLAGS}" PARENT_SCOPE)
        else()
            message(AUTHOR_WARNING "clang-tidy not found.")
        endif()
    endif()

    if(ENABLE_CPPCHECK)
        find_program(CPPCHECK_PATH cppcheck)
        if(CPPCHECK_PATH)
            message(STATUS "Found cppcheck: ${CPPCHECK_PATH}")
            set(CPPCHECK_ARGS "${CPPCHECK_PATH};--enable=all;--inconclusive;--force;--inline-suppr;--suppress=missingIncludeSystem")
            if(ENABLE_WERROR)
                list(APPEND CPPCHECK_ARGS "--error-exitcode=1")
            endif()
            set(CMAKE_CXX_CPPCHECK "${CPPCHECK_ARGS}" PARENT_SCOPE)
        else()
            message(AUTHOR_WARNING "cppcheck not found.")
        endif()
    endif()
endfunction()
