name: Create Python venvs

on:
  workflow_dispatch: {}
  push:
    branches: [main]

jobs:
  create-envs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Create venv (no packages)
        run: |
          python -u scripts/setup_python_env.py --env .venv
        shell: bash
